In [1]:
import pandas as pd

In [6]:
pd.read_csv('/home/staff/iinf/mw404851/mfMap.py/scripts/data/COADREAD/features_exp.txt', sep='\t')

,barcode,01BR001,01BR008,01BR010,01BR015,01BR018,01BR020,01BR027,01BR030,01BR031,...,TCGA-ZP-A9D2,TCGA-ZP-A9D4,TCGA-ZQ-A9CR,TCGA-ZR-A9CJ,TCGA-ZS-A9CD,TCGA-ZS-A9CE,TCGA-ZS-A9CF,TCGA-ZS-A9CG,TCGA-ZU-A8S4,TCGA-ZX-AA5X
0,ABI1,64.2557,38.5475,41.4999,55.4033,61.3736,65.4064,133.0723,39.8921,68.1891,...,82.9156,28.8747,35.2951,76.3105,19.0332,26.0706,21.37015,18.0213,37.93185,59.1590
1,ABI2,3.0340,2.7950,4.2455,4.6045,9.8698,7.0184,7.9108,4.3663,7.7196,...,8.4356,1.6041,3.4980,6.4658,0.8795,0.6815,1.86735,1.0200,5.52085,3.6170
2,ABL1,11.4315,10.3734,33.4159,33.4278,22.7797,18.2615,20.8920,15.5182,21.2659,...,22.8482,21.7750,38.7484,68.6578,12.5332,11.7897,21.01375,16.5968,32.86530,42.7654
3,ABL2,7.1285,6.9426,6.2088,9.3306,12.4836,7.3394,12.9617,6.4469,8.1613,...,7.9582,3.9289,8.0958,24.2672,2.8365,1.9057,4.97000,2.8940,8.99040,7.7885
4,ACP1,31.9342,54.0021,67.2826,43.6348,52.3882,100.2150,77.8713,41.9310,35.4987,...,134.8770,54.2376,44.6731,62.7264,36.6749,51.9248,53.90645,41.6052,36.89200,44.5866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,ZHX2,17.3141,21.0624,13.6053,28.4380,68.5013,5.7197,103.9557,36.0383,6.8604,...,26.6167,33.7463,11.6112,25.1392,34.0176,21.0961,18.32185,54.9006,16.08355,22.2086
775,ZMYM2,16.3632,12.9978,35.1968,43.2128,35.3521,29.9759,26.4796,25.0685,23.0270,...,24.2812,5.0126,7.9887,26.9854,3.7298,2.1463,7.51280,5.0108,6.07290,15.7269
776,ZNF250,6.1054,6.6347,7.1866,10.8138,11.6741,10.6063,8.4483,7.3260,7.4678,...,4.1345,2.1683,1.0918,4.3700,3.2780,1.5114,2.81435,3.1871,2.32340,4.3957
777,ZSCAN21,3.3110,7.5441,7.2537,4.4908,9.1308,8.1613,7.6386,5.0513,10.4287,...,14.6903,5.3227,1.8386,2.8506,2.8670,5.8399,4.18340,4.2312,3.27940,4.7728
778,ZZEF1,5.0735,7.7330,12.2909,13.1416,9.6493,7.5345,6.0720,11.5899,10.6627,...,6.8823,2.5039,5.7724,15.5820,3.7525,2.5498,4.45915,3.7502,7.04505,10.2757

In [11]:
pd.read_csv('/home/staff/iinf/mw404851/mfMap.py/scripts/data/COADREAD/features_mut_cnv_comb.txt', sep='\t')

,barcode,01BR001,01BR008,01BR010,01BR015,01BR018,01BR020,01BR027,01BR030,01BR031,...,TCGA-ZP-A9D2,TCGA-ZP-A9D4,TCGA-ZQ-A9CR,TCGA-ZR-A9CJ,TCGA-ZS-A9CD,TCGA-ZS-A9CE,TCGA-ZS-A9CF,TCGA-ZS-A9CG,TCGA-ZU-A8S4,TCGA-ZX-AA5X
0,ABL1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ADAM15,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AGT,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ANXA2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,APC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,ZBTB34,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
254,ZEB1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
255,ZEB2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
256,ZHX2,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
257,ZZEF1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
import pandas as pd
pd.read_csv('/home/staff/iinf/mw404851/mfMap.py/scripts/data/COADREAD/dataset_labels.txt', sep='\t')['subtype']

0                                   Breast
1                                   Breast
2                                   Breast
3                                   Breast
4                                   Breast
                       ...
11580    Liver and intrahepatic bile ducts
11581    Liver and intrahepatic bile ducts
11582    Liver and intrahepatic bile ducts
11583    Liver and intrahepatic bile ducts
11584                         Cervix uteri
Name: subtype, Length: 11585, dtype: str